// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef CWISSTABLE_INTERNAL_EXTRACT_H_
#define CWISSTABLE_INTERNAL_EXTRACT_H_

/// Macro keyword-arguments machinery.
///
/// This file defines a number of macros used by policy.h to implement its
/// policy construction macros.
///
/// The way they work is more-or-less like this:
///
/// `CWISS_EXTRACT(foo, ...)` will find the first parenthesized pair that
/// matches exactly `(foo, whatever)`, where `foo` is part of a small set of
/// tokens defined in this file. To do so, this first expands into
///
/// ```
/// CWISS_EXTRACT1(CWISS_EXTRACT_foo, (k, v), ...)
/// ```
///
/// where `(k, v)` is the first pair in the macro arguments. This in turn
/// expands into
///
/// ```
/// CWISS_SELECT01(CWISS_EXTRACT_foo (k, v), CWISS_EXTRACT_VALUE, (k, v),
/// CWISS_EXTRACT2, (needle, __VA_ARGS__), CWISS_NOTHING)
/// ```
///
/// At this point, the preprocessor will expand `CWISS_EXTRACT_foo (k, v)` into
/// `CWISS_EXTRACT_foo_k`, which will be further expanded into `tok,tok,tok` if
/// `k` is the token `foo`, because we've defined `CWISS_EXTRACT_foo_foo` as a
/// macro.
///
/// `CWISS_SELECT01` will then delete the first three arguments, and the fourth
/// and fifth arguments will be juxtaposed.
///
/// In the case that `k` does not match, `CWISS_EXTRACT_foo (k, v), IDENT, (k,
/// v),` is deleted from the call, and the rest of the macro expands into
/// `CWISS_EXTRACT2(needle, __VA_ARGS__, _)` repeating the cycle but with a
/// different name.
///
/// In the case that `k` matches, the `tok,tok,tok` is deleted, and we get
/// `CWISS_EXTRACT_VALUE(k, v)`, which expands to `v`.

#define CWISS_EXTRACT(needle_, default_, ...) \
  CWISS_EXTRACT00(CWISS_EXTRACT_##needle_, __VA_ARGS__, (needle_, default_))

#define CWISS_EXTRACT_VALUE(key, val) (val)

// NOTE: Everything below this line is generated by cwisstable/extract.py!

#define CWISS_EXTRACT_obj_copy(key, val) CWISS_EXTRACT_obj_copyZ##key
#define CWISS_EXTRACT_obj_copyZobj_copy \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_obj_dtor(key, val) CWISS_EXTRACT_obj_dtorZ##key
#define CWISS_EXTRACT_obj_dtorZobj_dtor \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_key_hash(key, val) CWISS_EXTRACT_key_hashZ##key
#define CWISS_EXTRACT_key_hashZkey_hash \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_key_eq(key, val) CWISS_EXTRACT_key_eqZ##key
#define CWISS_EXTRACT_key_eqZkey_eq CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_alloc_alloc(key, val) CWISS_EXTRACT_alloc_allocZ##key
#define CWISS_EXTRACT_alloc_allocZalloc_alloc \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_alloc_free(key, val) CWISS_EXTRACT_alloc_freeZ##key
#define CWISS_EXTRACT_alloc_freeZalloc_free \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_slot_size(key, val) CWISS_EXTRACT_slot_sizeZ##key
#define CWISS_EXTRACT_slot_sizeZslot_size \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_slot_align(key, val) CWISS_EXTRACT_slot_alignZ##key
#define CWISS_EXTRACT_slot_alignZslot_align \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_slot_init(key, val) CWISS_EXTRACT_slot_initZ##key
#define CWISS_EXTRACT_slot_initZslot_init \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_slot_transfer(key, val) CWISS_EXTRACT_slot_transferZ##key
#define CWISS_EXTRACT_slot_transferZslot_transfer \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_slot_get(key, val) CWISS_EXTRACT_slot_getZ##key
#define CWISS_EXTRACT_slot_getZslot_get \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING
#define CWISS_EXTRACT_slot_dtor(key, val) CWISS_EXTRACT_slot_dtorZ##key
#define CWISS_EXTRACT_slot_dtorZslot_dtor \
  CWISS_NOTHING, CWISS_NOTHING, CWISS_NOTHING

#define CWISS_EXTRACT00(needle, kv, ...)                              \
  CWISS_SELECT00(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT01, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT01(needle, kv, ...)                              \
  CWISS_SELECT01(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT02, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT02(needle, kv, ...)                              \
  CWISS_SELECT02(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT03, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT03(needle, kv, ...)                              \
  CWISS_SELECT03(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT04, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT04(needle, kv, ...)                              \
  CWISS_SELECT04(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT05, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT05(needle, kv, ...)                              \
  CWISS_SELECT05(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT06, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT06(needle, kv, ...)                              \
  CWISS_SELECT06(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT07, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT07(needle, kv, ...)                              \
  CWISS_SELECT07(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT08, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT08(needle, kv, ...)                              \
  CWISS_SELECT08(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT09, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT09(needle, kv, ...)                              \
  CWISS_SELECT09(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT0A, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT0A(needle, kv, ...)                              \
  CWISS_SELECT0A(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT0B, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT0B(needle, kv, ...)                              \
  CWISS_SELECT0B(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT0C, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT0C(needle, kv, ...)                              \
  CWISS_SELECT0C(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT0D, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT0D(needle, kv, ...)                              \
  CWISS_SELECT0D(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT0E, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT0E(needle, kv, ...)                              \
  CWISS_SELECT0E(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT0F, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT0F(needle, kv, ...)                              \
  CWISS_SELECT0F(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT10, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT10(needle, kv, ...)                              \
  CWISS_SELECT10(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT11, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT11(needle, kv, ...)                              \
  CWISS_SELECT11(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT12, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT12(needle, kv, ...)                              \
  CWISS_SELECT12(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT13, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT13(needle, kv, ...)                              \
  CWISS_SELECT13(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT14, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT14(needle, kv, ...)                              \
  CWISS_SELECT14(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT15, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT15(needle, kv, ...)                              \
  CWISS_SELECT15(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT16, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT16(needle, kv, ...)                              \
  CWISS_SELECT16(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT17, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT17(needle, kv, ...)                              \
  CWISS_SELECT17(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT18, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT18(needle, kv, ...)                              \
  CWISS_SELECT18(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT19, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT19(needle, kv, ...)                              \
  CWISS_SELECT19(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT1A, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT1A(needle, kv, ...)                              \
  CWISS_SELECT1A(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT1B, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT1B(needle, kv, ...)                              \
  CWISS_SELECT1B(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT1C, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT1C(needle, kv, ...)                              \
  CWISS_SELECT1C(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT1D, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT1D(needle, kv, ...)                              \
  CWISS_SELECT1D(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT1E, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT1E(needle, kv, ...)                              \
  CWISS_SELECT1E(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT1F, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT1F(needle, kv, ...)                              \
  CWISS_SELECT1F(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT20, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT20(needle, kv, ...)                              \
  CWISS_SELECT20(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT21, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT21(needle, kv, ...)                              \
  CWISS_SELECT21(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT22, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT22(needle, kv, ...)                              \
  CWISS_SELECT22(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT23, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT23(needle, kv, ...)                              \
  CWISS_SELECT23(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT24, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT24(needle, kv, ...)                              \
  CWISS_SELECT24(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT25, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT25(needle, kv, ...)                              \
  CWISS_SELECT25(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT26, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT26(needle, kv, ...)                              \
  CWISS_SELECT26(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT27, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT27(needle, kv, ...)                              \
  CWISS_SELECT27(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT28, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT28(needle, kv, ...)                              \
  CWISS_SELECT28(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT29, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT29(needle, kv, ...)                              \
  CWISS_SELECT29(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT2A, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT2A(needle, kv, ...)                              \
  CWISS_SELECT2A(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT2B, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT2B(needle, kv, ...)                              \
  CWISS_SELECT2B(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT2C, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT2C(needle, kv, ...)                              \
  CWISS_SELECT2C(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT2D, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT2D(needle, kv, ...)                              \
  CWISS_SELECT2D(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT2E, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT2E(needle, kv, ...)                              \
  CWISS_SELECT2E(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT2F, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT2F(needle, kv, ...)                              \
  CWISS_SELECT2F(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT30, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT30(needle, kv, ...)                              \
  CWISS_SELECT30(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT31, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT31(needle, kv, ...)                              \
  CWISS_SELECT31(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT32, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT32(needle, kv, ...)                              \
  CWISS_SELECT32(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT33, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT33(needle, kv, ...)                              \
  CWISS_SELECT33(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT34, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT34(needle, kv, ...)                              \
  CWISS_SELECT34(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT35, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT35(needle, kv, ...)                              \
  CWISS_SELECT35(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT36, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT36(needle, kv, ...)                              \
  CWISS_SELECT36(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT37, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT37(needle, kv, ...)                              \
  CWISS_SELECT37(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT38, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT38(needle, kv, ...)                              \
  CWISS_SELECT38(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT39, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT39(needle, kv, ...)                              \
  CWISS_SELECT39(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT3A, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT3A(needle, kv, ...)                              \
  CWISS_SELECT3A(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT3B, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT3B(needle, kv, ...)                              \
  CWISS_SELECT3B(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT3C, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT3C(needle, kv, ...)                              \
  CWISS_SELECT3C(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT3D, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT3D(needle, kv, ...)                              \
  CWISS_SELECT3D(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT3E, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT3E(needle, kv, ...)                              \
  CWISS_SELECT3E(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT3F, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)
#define CWISS_EXTRACT3F(needle, kv, ...)                              \
  CWISS_SELECT3F(needle kv, CWISS_EXTRACT_VALUE, kv, CWISS_EXTRACT40, \
                 (needle, __VA_ARGS__), CWISS_NOTHING)

#define CWISS_SELECT00(x, ...) CWISS_SELECT00_(x, __VA_ARGS__)
#define CWISS_SELECT01(x, ...) CWISS_SELECT01_(x, __VA_ARGS__)
#define CWISS_SELECT02(x, ...) CWISS_SELECT02_(x, __VA_ARGS__)
#define CWISS_SELECT03(x, ...) CWISS_SELECT03_(x, __VA_ARGS__)
#define CWISS_SELECT04(x, ...) CWISS_SELECT04_(x, __VA_ARGS__)
#define CWISS_SELECT05(x, ...) CWISS_SELECT05_(x, __VA_ARGS__)
#define CWISS_SELECT06(x, ...) CWISS_SELECT06_(x, __VA_ARGS__)
#define CWISS_SELECT07(x, ...) CWISS_SELECT07_(x, __VA_ARGS__)
#define CWISS_SELECT08(x, ...) CWISS_SELECT08_(x, __VA_ARGS__)
#define CWISS_SELECT09(x, ...) CWISS_SELECT09_(x, __VA_ARGS__)
#define CWISS_SELECT0A(x, ...) CWISS_SELECT0A_(x, __VA_ARGS__)
#define CWISS_SELECT0B(x, ...) CWISS_SELECT0B_(x, __VA_ARGS__)
#define CWISS_SELECT0C(x, ...) CWISS_SELECT0C_(x, __VA_ARGS__)
#define CWISS_SELECT0D(x, ...) CWISS_SELECT0D_(x, __VA_ARGS__)
#define CWISS_SELECT0E(x, ...) CWISS_SELECT0E_(x, __VA_ARGS__)
#define CWISS_SELECT0F(x, ...) CWISS_SELECT0F_(x, __VA_ARGS__)
#define CWISS_SELECT10(x, ...) CWISS_SELECT10_(x, __VA_ARGS__)
#define CWISS_SELECT11(x, ...) CWISS_SELECT11_(x, __VA_ARGS__)
#define CWISS_SELECT12(x, ...) CWISS_SELECT12_(x, __VA_ARGS__)
#define CWISS_SELECT13(x, ...) CWISS_SELECT13_(x, __VA_ARGS__)
#define CWISS_SELECT14(x, ...) CWISS_SELECT14_(x, __VA_ARGS__)
#define CWISS_SELECT15(x, ...) CWISS_SELECT15_(x, __VA_ARGS__)
#define CWISS_SELECT16(x, ...) CWISS_SELECT16_(x, __VA_ARGS__)
#define CWISS_SELECT17(x, ...) CWISS_SELECT17_(x, __VA_ARGS__)
#define CWISS_SELECT18(x, ...) CWISS_SELECT18_(x, __VA_ARGS__)
#define CWISS_SELECT19(x, ...) CWISS_SELECT19_(x, __VA_ARGS__)
#define CWISS_SELECT1A(x, ...) CWISS_SELECT1A_(x, __VA_ARGS__)
#define CWISS_SELECT1B(x, ...) CWISS_SELECT1B_(x, __VA_ARGS__)
#define CWISS_SELECT1C(x, ...) CWISS_SELECT1C_(x, __VA_ARGS__)
#define CWISS_SELECT1D(x, ...) CWISS_SELECT1D_(x, __VA_ARGS__)
#define CWISS_SELECT1E(x, ...) CWISS_SELECT1E_(x, __VA_ARGS__)
#define CWISS_SELECT1F(x, ...) CWISS_SELECT1F_(x, __VA_ARGS__)
#define CWISS_SELECT20(x, ...) CWISS_SELECT20_(x, __VA_ARGS__)
#define CWISS_SELECT21(x, ...) CWISS_SELECT21_(x, __VA_ARGS__)
#define CWISS_SELECT22(x, ...) CWISS_SELECT22_(x, __VA_ARGS__)
#define CWISS_SELECT23(x, ...) CWISS_SELECT23_(x, __VA_ARGS__)
#define CWISS_SELECT24(x, ...) CWISS_SELECT24_(x, __VA_ARGS__)
#define CWISS_SELECT25(x, ...) CWISS_SELECT25_(x, __VA_ARGS__)
#define CWISS_SELECT26(x, ...) CWISS_SELECT26_(x, __VA_ARGS__)
#define CWISS_SELECT27(x, ...) CWISS_SELECT27_(x, __VA_ARGS__)
#define CWISS_SELECT28(x, ...) CWISS_SELECT28_(x, __VA_ARGS__)
#define CWISS_SELECT29(x, ...) CWISS_SELECT29_(x, __VA_ARGS__)
#define CWISS_SELECT2A(x, ...) CWISS_SELECT2A_(x, __VA_ARGS__)
#define CWISS_SELECT2B(x, ...) CWISS_SELECT2B_(x, __VA_ARGS__)
#define CWISS_SELECT2C(x, ...) CWISS_SELECT2C_(x, __VA_ARGS__)
#define CWISS_SELECT2D(x, ...) CWISS_SELECT2D_(x, __VA_ARGS__)
#define CWISS_SELECT2E(x, ...) CWISS_SELECT2E_(x, __VA_ARGS__)
#define CWISS_SELECT2F(x, ...) CWISS_SELECT2F_(x, __VA_ARGS__)
#define CWISS_SELECT30(x, ...) CWISS_SELECT30_(x, __VA_ARGS__)
#define CWISS_SELECT31(x, ...) CWISS_SELECT31_(x, __VA_ARGS__)
#define CWISS_SELECT32(x, ...) CWISS_SELECT32_(x, __VA_ARGS__)
#define CWISS_SELECT33(x, ...) CWISS_SELECT33_(x, __VA_ARGS__)
#define CWISS_SELECT34(x, ...) CWISS_SELECT34_(x, __VA_ARGS__)
#define CWISS_SELECT35(x, ...) CWISS_SELECT35_(x, __VA_ARGS__)
#define CWISS_SELECT36(x, ...) CWISS_SELECT36_(x, __VA_ARGS__)
#define CWISS_SELECT37(x, ...) CWISS_SELECT37_(x, __VA_ARGS__)
#define CWISS_SELECT38(x, ...) CWISS_SELECT38_(x, __VA_ARGS__)
#define CWISS_SELECT39(x, ...) CWISS_SELECT39_(x, __VA_ARGS__)
#define CWISS_SELECT3A(x, ...) CWISS_SELECT3A_(x, __VA_ARGS__)
#define CWISS_SELECT3B(x, ...) CWISS_SELECT3B_(x, __VA_ARGS__)
#define CWISS_SELECT3C(x, ...) CWISS_SELECT3C_(x, __VA_ARGS__)
#define CWISS_SELECT3D(x, ...) CWISS_SELECT3D_(x, __VA_ARGS__)
#define CWISS_SELECT3E(x, ...) CWISS_SELECT3E_(x, __VA_ARGS__)
#define CWISS_SELECT3F(x, ...) CWISS_SELECT3F_(x, __VA_ARGS__)

#define CWISS_SELECT00_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT01_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT02_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT03_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT04_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT05_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT06_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT07_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT08_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT09_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT0A_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT0B_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT0C_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT0D_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT0E_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT0F_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT10_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT11_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT12_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT13_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT14_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT15_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT16_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT17_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT18_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT19_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT1A_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT1B_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT1C_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT1D_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT1E_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT1F_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT20_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT21_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT22_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT23_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT24_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT25_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT26_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT27_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT28_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT29_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT2A_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT2B_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT2C_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT2D_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT2E_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT2F_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT30_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT31_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT32_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT33_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT34_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT35_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT36_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT37_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT38_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT39_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT3A_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT3B_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT3C_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT3D_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT3E_(_1, _2, _3, call, args, ...) call args
#define CWISS_SELECT3F_(_1, _2, _3, call, args, ...) call args

#endif  // CWISSTABLE_INTERNAL_EXTRACT_H_
